---
- hosts: master
  become: yes
  tasks:

   - name: Update apt cache # apt-get update
     apt:
       update_cache: yes
       
   - name: install SW 
     apt:
       name: "{{ item }}" 
       state: present
     with_items:
      - tree
  



