---
- hosts: master
  become: yes
  tasks:

   - name: Update apt cache # apt-get update
     apt:
       update_cache: yes
       
   - name: install SW # make sure 'tree' is installed
     apt:
       name: tree 
       state: present

  



