---
- hosts: master
  become: yes

  tasks:
  - name: Update apt cache # apt-get update
    apt:
      update_cache: yes

  - name: remove SW # make sure'tree' is absent
    apt:
      name: tree 
      state: absent

  - name: test # check if 'tree' is there, ignore errors => don't exit the play
    shell: tree
    register: shell_cmd
    failed_when: shell_cmd.rc != 0
    ignore_errors: True
    changed_when: False
    
  - name: debugging # look into the content of the results of the shell cmd, we chose to store it in 'shell_cmd' variable
    debug: msg="{{shell_cmd}}"
    

  - name: install SW # make sure 'tree' and 'sl' are installed
    apt:
      name: "{{ item }}" 
      state: present
    with_items:
    - tree
    - sl
    when: shell_cmd.rc != 0
   
       